name: "PR Slack-Notication Integration"

on:
  pull_request:
    types: [opened, reopened, edited, closed]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github-token: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
