name: "PR Slack-Notication Integration"

on:
  pull_request:
    types: [opened, reopened, edited, closed]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          gh-token: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          slack-token: ${{ secrets.ACCESS_SLACK_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
